#!/bin/bash

x=$PWD

NC='\033[0m'                            # No Color.

VI='\033[0;95m'                         # Violet.
YE='\033[1;93m'                         # Yellow.
CYA='\033[0;96m'                        # Cyan.
GR='\033[0;32m'                         # Green.
BAD='\033[0;91m'                        # Strong red. For errors.

update()
{
  echo -e "${CYA}THEOS${NC}"
  cd $THEOS || exit
  git pull
  git submodule update --init --recursive
  echo -e "${CYA}SDKs${NC}"
  cd $THEOS/sdks || exit
  git pull
  git submodule update --init --recursive
  echo -e "${CYA}COMMAND${NC}"
  cd $HOME/TheosScript || exit
  git pull
  git submodule update --init --recursive
  cd $x || exit
}

usage()
{
    echo ""
    echo -e "${CYA}THEOS${NC}"
    echo "usage: theos [commands]"
    echo ""
    echo -e "${CYA}BUILDING${NC}"
    echo -e "${VI}-b | --build${NC} | Builds a package."
    echo ""
    echo -e "${CYA}MISC${NC}"
    echo -e "${VI}-c | --checkra1n${NC} | Opens checkra1n."
    echo ""
    echo -e "${VI}-s | --ssh${NC} | SSH to the IP that you selected."
    echo ""
    echo -e "${VI}-dr | --devicerun | Run a command on the device's IP that you selected."
    echo ""
    echo -e "${VI}-r | --respring | Resprings on your development device."
    echo ""
    echo -e "${CYA}CONFIG${NC}"
    echo -e "${VI}-u | --update${NC} | Updates Theos."
    echo ""
    echo -e "${VI}-n | --nic${NC} | Runs nic.pl."
    echo ""
    echo -e "${CYA}INSTALL${NC}"
    echo -e "${VI}-cl | --clang${NC} | Installs the latest clang toolchain."
    echo ""
    echo -e "${VI}-inst | --install${NC} | Installs Theos."
    echo ""
}

checkra1n()
{
    fakeroot checkra1n
}

install()
{
    echo -e "${CYA}Installing dependencies...${NC}"
    sudo apt-get install fakeroot git perl clang-6.0 build-essential
    echo -e "${CYA}Instantiating variables...${NC}"
    echo "export THEOS=~/theos" >> ~/.profile
    echo "export THEOS=~/theos" >> ~/.bashrc
    echo -e "${CYA}Cloning theos...${NC}"
    git clone --recursive https://github.com/theos/theos.git $HOME/theos
    rm -rf $HOME/theos/sdks
    echo -e "${CYA}Getting toolchain...${NC}"
    cd $HOME
    curl -LO https://github.com/sbingner/llvm-project/releases/download/v10.0.0-1/linux-ios-arm64e-clang-toolchain.tar.lzma
    tar -xvf $HOME/linux-ios-arm64e-clang-toolchain.tar.lzma
    sudo mkdir -p $HOME/theos/toolchain/linux/iphone
    sudo mv ios-arm64e-clang-toolchain/* $HOME/theos/toolchain/linux/iphone
    rm -rf ios-arm64e-clang-toolchain
    rm -rf linux-ios-arm64e-clang-toolchain.tar.lzma
    echo -e "${CYA}Getting SDKs...${NC}"
    git clone https://github.com/xybp888/iOS-SDKS $THEOS/sdks
    cd $x
    echo -e "${CYA}Installation is done. In order for the theos variable to take place, you must restart your terminal.${NC}"
}

while [ "$1" != "" ]; do
    case $1 in
        -u | --update)              update
                                exit
                                ;;
        -c | --checkra1n)           checkra1n
                                exit
                                ;;
        -n | --nic)                 $THEOS/bin/nic.pl
                                exit
                                ;;
        -b | --build)               make clean package FINALPACKAGE=1
                                exit
                                ;;
        -cl | --clang)              sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
                                exit
                                ;;
        -inst | --install)          install
                                exit
                                ;;
        -s | --ssh)                 ssh mobile@$THEOS_DEVICE_IP
                                exit
                                ;;
        -dr | --devicerun)      shift
                                    ssh root@$THEOS_DEVICE_IP "$*"
                                exit
                                ;;
        -r | --respring)            ssh root@$THEOS_DEVICE_IP "killall SpringBoard"
                                exit
                                ;;
    esac
    shift
done

if [ "$1" == "" ]; then
  usage
  exit
fi